<?php
/**
* English file for plugin djg_rss
*
* @package wolf
* @subpackage djg_rss
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast <djgprv@gmail.com>
*
**/
return array(
/** DjgRssController.php */ 
'Your settings have been updated' => 'Your settings have been updated', 
'The settings have been saved.' => 'The settings have been saved.', 
'An error occured trying to save the settings.' => 'An error occured trying to save the settings.', 
'Could not save settings, no settings found.' => 'Could not save settings, no settings found.', 
/** enable.php */ 
'Successfully installed plugin.' => 'Successfully installed plugin.', 
/** index.php */ 
'[djg] RSS Feed' => '[djg] RSS Feed', 
'RSS Feed generator' => 'RSS Feed generator', 
/** views\documentation.php */ 
'Documentation' => 'Documentation', 
/** views\settings.php */ 
'Settings' => 'Settings', 
'Generator' => 'Generator', 
'Managing Editor' => 'Managing Editor', 
'Web Master' => 'Web Master', 
'Max <strong>feeds</strong> per chanel' => 'Max <strong>feeds</strong> per chanel', 
'Save' => 'Save', 
'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.' => 'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.', 
/** views\sidebar.php */ 
);