<?php
/**
* English file for plugin djg_rss
*
* @package wolf
* @subpackage djg_rss
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast <djgprv@gmail.com>
*
**/
return array(
/** DjgRssController.php */ 
'The settings have been updated.' => 'The settings have been updated.', 
/** index.php */ 
'[djg] RSS Feed' => '[djg] RSS Feed', 
'RSS Feed generator' => 'RSS Feed generator', 
/** views\documentation.php */ 
'Documentation' => 'Documentation', 
/** views\settings.php */ 
'Settings' => 'Settings', 
'Generator' => 'Generator',
'Display channel content' => 'Display channel content',
'Managing Editor' => 'Managing Editor', 
'Web Master' => 'Web Master', 
'Max feeds per channel' => 'Max <strong>feeds</strong> per channel', 
'Language' => 'Language', 
'Save' => 'Save', 
'You have modified this page. If you navigate away from this page without first saving your data' => 'You have modified this page.  If you navigate away from this page without first saving your data', 
/** views\sidebar.php */ 
);